<a href="https://colab.research.google.com/github/Anoshawott/Foundations-of-Business-Analytics-QBUS1040/blob/master/Problem3_student_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
        #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - np.inner(q[j], a[i])*q[j]
        
        #Test for dependennce
        if np.linalg.norm(q_tilde) <= 1e-6: #1e-6 = 0.000001
            print("Vectors are linearly dependent.")
            print ("GS algorithm terminates at iteration ", i+1)
            return q
        
        #Normalization
        else:
            qi = q_tilde / np.linalg.norm(q_tilde) #linalg == linear algebra library
            q.append(qi)
    print("Vectors are linearly independent.")
    return q

import numpy as np
# a linear independent example
a_list = np.array([[0,0,1,0], [1,1,0,0], [1,-1,0,0], [1,1,1,4]])
result = np.array(gram_schmidt(a_list))
print(result)

yo = np.array(gram_schmidt(result))
print(yo)

# a linear dependent example
b_list = np.array([[0,0,1,0], [1,1,0,0], [2,2,0,0], [3,3,0,0]])
result = np.array(gram_schmidt(b_list))
print(result)



Vectors are linearly independent.
[[ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 7.07106781e-01  7.07106781e-01  0.00000000e+00  0.00000000e+00]
 [ 7.07106781e-01 -7.07106781e-01  0.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17  5.55111512e-17  0.00000000e+00  1.00000000e+00]]
Vectors are linearly independent.
[[ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 7.07106781e-01  7.07106781e-01  0.00000000e+00  0.00000000e+00]
 [ 7.07106781e-01 -7.07106781e-01  0.00000000e+00  0.00000000e+00]
 [-1.23259516e-32 -1.23259516e-32  0.00000000e+00  1.00000000e+00]]
Vectors are linearly dependent.
GS algorithm terminates at iteration  3
[[0.         0.         1.         0.        ]
 [0.70710678 0.70710678 0.         0.        ]]


# Probelm 3(b) in tutorial 5

In [0]:
c_list = np.array([[768,-2095,4093,834,-7383],[1121,-9284,-3490,1428,1435],
                  [3425,5821,-7249,4392,23450],[8023,-6342,8241,5835,-293]])
result = np.array(gram_schmidt(c_list))
print(result)


Vectors are linearly independent.
[[ 0.08755826 -0.23884709  0.46663539  0.0950828  -0.84172222]
 [ 0.11345856 -0.92125322 -0.32526232  0.1439081   0.10915377]
 [ 0.54193775  0.0665187   0.40236716  0.65429827  0.33447448]
 [ 0.2353082  -0.23738921  0.56173775 -0.68291876  0.32611207]]


In [0]:
b_list = np.array([[1,1], [1,1]])
result = np.array(gram_schmidt(b_list))
print(result)

Vectors are linearly dependent.
GS algorithm terminates at iteration  2
[[0.70710678 0.70710678]]
